# -*- coding: utf-8 -*-
"""Copy of QCD_6_2_last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPK12A4C_2WjKxmQDK9eEsjb1YRgSTP6
"""

!pip install kaggle

!pip install tensorflowjs

# Manufacturing Defect Detection - Complete Training Pipeline
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import os
import json
from zipfile import ZipFile
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt
import shutil
import seaborn as sns
from sklearn.metrics import roc_curve, auc
from tensorflow.keras.models import Model
import tensorflowjs as tfjs

# Install required packages
!pip install kaggle tensorflow scikit-learn pandas matplotlib

# Setup Kaggle credentials
try:
    kaggle_dictionary = json.load(open("kaggle.json"))
    os.environ["KAGGLE_USERNAME"] = kaggle_dictionary["username"]
    os.environ["KAGGLE_KEY"] = kaggle_dictionary["key"]
    print("Kaggle credentials loaded successfully")
except FileNotFoundError:
    print("kaggle.json not found. Please ensure Kaggle API credentials are set up.")

# Download dataset
!kaggle datasets download -d yidazhang07/bridge-cracks-image

!ls

# unzip the dataset file
with ZipFile("bridge-cracks-image.zip", "r") as zip_ref:
  zip_ref.extractall()

!ls

data = "/content/Bridge_Crack_Image/DBCC_Training_Data_Set"

base_path = '/content/Bridge_Crack_Image/DBCC_Training_Data_Set/train'
crack_dir = os.path.join(base_path, 'crack')
no_crack_dir = os.path.join(base_path, 'no_crack')

# Create folders
os.makedirs(crack_dir, exist_ok=True)
os.makedirs(no_crack_dir, exist_ok=True)

# Move images
for fname in os.listdir(base_path):
    fpath = os.path.join(base_path, fname)
    if os.path.isfile(fpath):
        if fname.lower().startswith('crack'):
            shutil.move(fpath, crack_dir)
        elif fname.lower().startswith('no'):
            shutil.move(fpath, no_crack_dir)

# Training data augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=True,  # Added for more augmentation
    brightness_range=[0.8, 1.2],  # Added for lighting variation
    fill_mode='nearest',
    validation_split=0.2
)

# Validation and test data (no augmentation, only rescaling)
val_test_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Create generators
train_generator = train_datagen.flow_from_directory(
    os.path.join(data, "train"),
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

validation_generator = val_test_datagen.flow_from_directory(
    os.path.join(data, "train"),
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

# Test generator (if test directory exists)
test_generator = None
test_dir = os.path.join(data, "test")
if os.path.exists(test_dir):
    test_generator = val_test_datagen.flow_from_directory(
        test_dir,
        target_size=(224, 224),
        batch_size=32,
        class_mode='categorical',
        shuffle=False
    )

print(f"Training samples: {train_generator.samples}")
print(f"Validation samples: {validation_generator.samples}")
if test_generator:
    print(f"Test samples: {test_generator.samples}")

print(f"Class indices: {train_generator.class_indices}")

# Create model
print("\nCreating model...")

# Load pre-trained MobileNetV2
def build_improved_model():
    base_model = tf.keras.applications.MobileNetV2(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet'
    )

    x = base_model.output
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.BatchNormalization()(x)

    # First dense block
    x = tf.keras.layers.Dense(512, activation='relu')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.5)(x)

    # Second dense block
    x = tf.keras.layers.Dense(256, activation='relu')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    outputs = tf.keras.layers.Dense(2, activation='softmax')(x)

    model = tf.keras.Model(inputs=base_model.input, outputs=outputs)
    return model, base_model

# Create model
model, base_model = build_improved_model()

# Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=[
        'accuracy',
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
        tf.keras.metrics.AUC(name='auc'),
        tf.keras.metrics.F1Score(name='f1', average='weighted')
    ]
)

print(f"Model created with {model.count_params():,} parameters")

# Create callbacks
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=5,
        min_lr=1e-7,
        verbose=1
    ),
    tf.keras.callbacks.ModelCheckpoint(
        'best_defect_model.h5',
        monitor='val_f1',
        mode='max',
        save_best_only=True,
        verbose=1
    ),
    tf.keras.callbacks.TensorBoard(
        log_dir='./logs',
        histogram_freq=1,
        write_graph=True,
        write_images=True,
        update_freq='epoch'
    )
]

# Train model
def compile_model(learning_rate=0.001):
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss='categorical_crossentropy',
        metrics=[
            'accuracy',
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall'),
            tf.keras.metrics.AUC(name='auc'),
            tf.keras.metrics.F1Score(name='f1', average='weighted')
        ]
    )

# Phase 1: Initial training
print("Phase 1: Training only the top layers...")
base_model.trainable = False
compile_model(learning_rate=0.001)
history1 = model.fit(
    train_generator,
    epochs=10,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

# Phase 2: Fine-tuning
print("Phase 2: Fine-tuning the model...")
base_model.trainable = True
for layer in base_model.layers[:-54]:  # Freeze first 100 layers
    layer.trainable = False

compile_model(learning_rate=0.0001)
history2 = model.fit(
    train_generator,
    epochs=20,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

# Plot combined training history
def plot_training_history(history1, history2):
    total_epochs = len(history1.history['loss']) + len(history2.history['loss'])
    epochs_range = range(1, total_epochs + 1)

    plt.figure(figsize=(15, 5))

    # Combine histories
    combined_history = {
        'accuracy': history1.history['accuracy'] + history2.history['accuracy'],
        'val_accuracy': history1.history['val_accuracy'] + history2.history['val_accuracy'],
        'loss': history1.history['loss'] + history2.history['loss'],
        'val_loss': history1.history['val_loss'] + history2.history['val_loss']
    }

    # Plot accuracy
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, combined_history['accuracy'], label='Training Accuracy')
    plt.plot(epochs_range, combined_history['val_accuracy'], label='Validation Accuracy')
    plt.title('Model Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # Plot loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, combined_history['loss'], label='Training Loss')
    plt.plot(epochs_range, combined_history['val_loss'], label='Validation Loss')
    plt.title('Model Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout()
    plt.show()

# Plot training history
plot_training_history(history1, history2)

# Evaluate model
def evaluate_model(model, generator, class_names):
    predictions = model.predict(generator)
    y_pred = np.argmax(predictions, axis=1)
    y_true = generator.labels

    print("\nModel Evaluation Results:")
    print("="*50)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names))

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    # ROC curve
    y_score = predictions[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_score)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='darkorange', lw=2,
             label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic')
    plt.legend(loc="lower right")
    plt.show()

# Evaluate the model
evaluate_model(model, validation_generator, ['Non-Defective', 'Defective'])

# Save model with metadata
model_version = "1.0.0"
model_metadata = {
    "version": model_version,
    "input_shape": [224, 224, 3],
    "classes": list(train_generator.class_indices.keys()),
    "preprocessing": {
        "rescale": 1./255,
        "target_size": [224, 224]
    }
}

# Save metadata
with open('model_metadata.json', 'w') as f:
    json.dump(model_metadata, f)

# Save Keras model
model.save(f'defect_detection_model_v{model_version}.h5')

# Convert to TensorFlow.js with metadata
tfjs.converters.save_keras_model(
    model,
    'tfjs_model',
    metadata={
        'version': model_version,
        'inputShape': [224, 224, 3],
        'classes': list(train_generator.class_indices.keys())
    }
)